### ISSUE TITLE
Automatic restores are failing

### ISSUE THREAD

**Issue by 8tomat8** [couchbase-partners/helm-charts#23]
**Context:**
We are using the [latest docker image](https://hub.docker.com/layers/couchbase/operator-backup/6.5.1-106/images/sha256-d02a93f6f68cc956d0954a81ade49eaae1d552edee3d6f2ef1ebda76d0e937fb?context=explore) of the couchbase operator-backup, as it fixes the full backup rotation.

We are trying to restore backups created automatically using next definition:
```yaml
apiVersion: couchbase.com/v2
kind: CouchbaseBackupRestore
metadata:
  name: couchbase-restore
spec:
  backup: couchbase-backup
  start:
    str: oldest
  backoffLimit: 2
  logRetention: 156h
```

**Issue:**
```log
2020-09-17 11:55:27,127 - root - INFO - epoch: 1600343727
2020-09-17 11:55:27,128 - root - INFO - timestamp: 2020-09-17T11_55_27
2020-09-17 11:55:27,128 - root - INFO - Namespace(backup_ret=None, cacert=None, cluster='couchbase-operator-couchbase-cluster', config=False, end='latest', log_ret='156.00', mode='restore', repo='couchbase-operator-couchbase-cluster-2020-09-17T03_00_20', start='latest', strategy=None, verbosity='INFO')
2020-09-17 11:55:27,128 - root - INFO - start logRetention check
2020-09-17 11:55:27,128 - root - INFO - removed 0 logs in /data/scriptlogs/restore
2020-09-17 11:55:27,128 - root - INFO - mode: RESTORE
mkdir: cannot create directory ‘/data/backups’: File exists
rm: cannot remove '/data/backups/lock.lk': No such file or directory
2020-09-17 11:55:27,133 - root - INFO - attempting to query K8S objects
2020-09-17 11:55:27,134 - root - INFO - k8s config loaded
2020-09-17 11:55:27,134 - root - INFO - working in namespace: default
Traceback (most recent call last):
  File "/opt/couchbase/bin/backup_script", line 1114, in <module>
    main()
  File "/opt/couchbase/bin/backup_script", line 158, in main
    k8s_setup(args)
  File "/opt/couchbase/bin/backup_script", line 408, in k8s_setup
    api_job_name = '-'.join(list(matches.group(1, 2)))
AttributeError: 'NoneType' object has no attribute 'group'
```

The regex ```matches = re.fullmatch(r'^(.*)-(\d+)-\w+', api_pod_name)``` do not match a pod name so the `matches` is None

**Comment by tahmmee** [comment]
Thanks @8tomat8 it's an issue and looks like a new image with the fix is on the way 
https://issues.couchbase.com/browse/K8S-1679

**Comment by danielma82** [comment]
Hi, we're aware of this issue and have a fix in the works for a new docker image. https://issues.couchbase.com/browse/K8S-1679

**Comment by 8tomat8** [comment]
Good to know, thanks!
Can you tell me if there is a stable version of the backup operator at this moment? Every version that we are trying to use has some bugs which appear only after extensive testing, which makes it very annoying to rely on.
We are ready to contact and show our use case and setup if you need it.

**Comment by tahmmee** [comment]
Hey @8tomat8 , we're working on getting a fix out.  Meanwhile, if you'd like some direct support on product issues you can reach out to us here: support.couchbase.com
